import{S as d,i as f}from"./assets/vendor-5b791d57.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();function m(){const r=document.querySelector(".loader");r.style.display="none"}function p(r){const s=`https://pixabay.com/api/?key=42578241-c2049137a4025890cf19aabd8&q=${r}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(s).then(c=>{if(!c.ok)throw new Error("Image error");return c.json()}).then(c=>{if(m(),c.hits.length===0)throw new Error("No images found");return c.hits})}function y(r){const o=document.querySelector(".gallery"),n=r.map(({webformatURL:i,largeImageURL:e,tags:t,likes:s,views:c,comments:l,downloads:u})=>`<li class="gallery-item">
                <a class="gallery-link" href="${e}">
                <img class="gallery-image"
                src="${i}"
                data-source="${e}"
                alt="${t}"/></a>
                <p>likes="${s}"</p>
                <p>views="${c}"</p>
                <p>comments="${l}"</p>
                <p>download="${u}"</p>
            </li>`).join("");o.insertAdjacentHTML("beforeend",n)}const h=document.querySelector("form"),g=document.querySelector(".search-btn"),E=document.querySelector(".gallery"),S=document.querySelector('input[type="text"]'),a=document.querySelector(".loader"),$=new d(".gallery a",{captionsData:"alt",captionDelay:250});function L(){a.style.display="block"}function A(){a.style.display="none"}function I(){E.innerHTML=""}function q(r){r.preventDefault();const o=S.value.trim();I(),L(),h.reset(),p(o).then(n=>{y(n),$.refresh()}).catch(n=>{A(),console.error(n.message),f.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})})}g.addEventListener("click",q);
//# sourceMappingURL=commonHelpers.js.map
